/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { BUTTON_SIZE, BUTTON_VARIANT } from "./components/siga-button/siga-button";
export { BUTTON_SIZE, BUTTON_VARIANT } from "./components/siga-button/siga-button";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface SigaButton {
        "disabled": boolean;
        "icon"?: string;
        "label"?: string;
        "size": BUTTON_SIZE;
        "variant": BUTTON_VARIANT;
    }
    interface SigaLogo {
        "altText": string;
        "height": string;
        "variant": 'regular' | 'inverted';
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSigaButtonElement extends Components.SigaButton, HTMLStencilElement {
    }
    var HTMLSigaButtonElement: {
        prototype: HTMLSigaButtonElement;
        new (): HTMLSigaButtonElement;
    };
    interface HTMLSigaLogoElement extends Components.SigaLogo, HTMLStencilElement {
    }
    var HTMLSigaLogoElement: {
        prototype: HTMLSigaLogoElement;
        new (): HTMLSigaLogoElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "siga-button": HTMLSigaButtonElement;
        "siga-logo": HTMLSigaLogoElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface SigaButton {
        "disabled"?: boolean;
        "icon"?: string;
        "label"?: string;
        "size"?: BUTTON_SIZE;
        "variant"?: BUTTON_VARIANT;
    }
    interface SigaLogo {
        "altText"?: string;
        "height"?: string;
        "variant"?: 'regular' | 'inverted';
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "siga-button": SigaButton;
        "siga-logo": SigaLogo;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "siga-button": LocalJSX.SigaButton & JSXBase.HTMLAttributes<HTMLSigaButtonElement>;
            "siga-logo": LocalJSX.SigaLogo & JSXBase.HTMLAttributes<HTMLSigaLogoElement>;
        }
    }
}
